
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm start
    db:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - dbdata:/data/db